### ISSUE TITLE
Change a kotlin's plugin phase to "process-sources"

### ISSUE THREAD

**Issue by ikonovalov** [b7w/credit#1]
**Plugin setup:**

`<plugin>
                <artifactId>kotlin-maven-plugin</artifactId>
                <groupId>org.jetbrains.kotlin</groupId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`

**Comment by b7w** [comment]
А pull request :-)

**Comment by ikonovalov** [comment]
Arghh...

**Comment by b7w** [comment]
Fix in https://github.com/b7w/credit/commit/a401d14606d1c733da4d960969cc630a5b7c8f1e

**Comment by ikonovalov** [comment]
Much better. Strange "package not found" errors disappeared too.
